# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Transaction.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'Transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11Transaction.proto\"d\n\rIntraShardReq\x12\x11\n\tclusterId\x18\x01 \x02(\x05\x12\x10\n\x08senderId\x18\x02 \x02(\x05\x12\x12\n\nreceiverId\x18\x03 \x02(\x05\x12\x0e\n\x06\x61mount\x18\x04 \x02(\x05\x12\n\n\x02id\x18\x05 \x02(\x05\"B\n\rIntraShardRsp\x12%\n\x06result\x18\x01 \x02(\x0e\x32\x15.IntraShardResultType\x12\n\n\x02id\x18\x02 \x02(\x05\"\xaa\x01\n\rCrossShardReq\x12#\n\x05phase\x18\x01 \x02(\x0e\x32\x14.CrossShardPhaseType\x12\x17\n\x0fsenderClusterId\x18\x02 \x02(\x05\x12\x19\n\x11receiverClusterId\x18\x03 \x02(\x05\x12\x10\n\x08senderId\x18\x04 \x02(\x05\x12\x12\n\nreceiverId\x18\x05 \x02(\x05\x12\x0e\n\x06\x61mount\x18\x06 \x02(\x05\x12\n\n\x02id\x18\x07 \x02(\x05\"B\n\rCrossShardRsp\x12%\n\x06result\x18\x01 \x02(\x0e\x32\x15.CrossShardResultType\x12\n\n\x02id\x18\x02 \x02(\x05\"+\n\x04Stop\x12\x11\n\tclusterId\x18\x01 \x02(\x05\x12\x10\n\x08serverId\x18\x02 \x02(\x05\"-\n\x06Resume\x12\x11\n\tclusterId\x18\x01 \x02(\x05\x12\x10\n\x08serverId\x18\x02 \x02(\x05*-\n\x14IntraShardResultType\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01*9\n\x13\x43rossShardPhaseType\x12\x0b\n\x07PREPARE\x10\x00\x12\n\n\x06\x43OMMIT\x10\x01\x12\t\n\x05\x41\x42ORT\x10\x02*0\n\x14\x43rossShardResultType\x12\x07\n\x03YES\x10\x00\x12\x06\n\x02NO\x10\x01\x12\x07\n\x03\x41\x43K\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTRASHARDRESULTTYPE']._serialized_start=524
  _globals['_INTRASHARDRESULTTYPE']._serialized_end=569
  _globals['_CROSSSHARDPHASETYPE']._serialized_start=571
  _globals['_CROSSSHARDPHASETYPE']._serialized_end=628
  _globals['_CROSSSHARDRESULTTYPE']._serialized_start=630
  _globals['_CROSSSHARDRESULTTYPE']._serialized_end=678
  _globals['_INTRASHARDREQ']._serialized_start=21
  _globals['_INTRASHARDREQ']._serialized_end=121
  _globals['_INTRASHARDRSP']._serialized_start=123
  _globals['_INTRASHARDRSP']._serialized_end=189
  _globals['_CROSSSHARDREQ']._serialized_start=192
  _globals['_CROSSSHARDREQ']._serialized_end=362
  _globals['_CROSSSHARDRSP']._serialized_start=364
  _globals['_CROSSSHARDRSP']._serialized_end=430
  _globals['_STOP']._serialized_start=432
  _globals['_STOP']._serialized_end=475
  _globals['_RESUME']._serialized_start=477
  _globals['_RESUME']._serialized_end=522
# @@protoc_insertion_point(module_scope)
