# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appendEntriesRsp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='appendEntriesRsp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x61ppendEntriesRsp.proto\"C\n\x10\x41ppendEntriesRsp\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x10\n\x08serverId\x18\x03 \x01(\x05\x62\x06proto3'
)




_APPENDENTRIESRSP = _descriptor.Descriptor(
  name='AppendEntriesRsp',
  full_name='AppendEntriesRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='AppendEntriesRsp.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='AppendEntriesRsp.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serverId', full_name='AppendEntriesRsp.serverId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['AppendEntriesRsp'] = _APPENDENTRIESRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppendEntriesRsp = _reflection.GeneratedProtocolMessageType('AppendEntriesRsp', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESRSP,
  '__module__' : 'appendEntriesRsp_pb2'
  # @@protoc_insertion_point(class_scope:AppendEntriesRsp)
  })
_sym_db.RegisterMessage(AppendEntriesRsp)


# @@protoc_insertion_point(module_scope)
