# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crossShardReq.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crossShardReq.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63rossShardReq.proto\"\xaa\x01\n\rCrossShardReq\x12#\n\x05phase\x18\x01 \x01(\x0e\x32\x14.CrossShardPhaseType\x12\x17\n\x0fsenderClusterId\x18\x02 \x01(\x05\x12\x19\n\x11receiverClusterId\x18\x03 \x01(\x05\x12\x10\n\x08senderId\x18\x04 \x01(\x05\x12\x12\n\nreceiverId\x18\x05 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x06 \x01(\x05\x12\n\n\x02id\x18\x07 \x01(\x05*9\n\x13\x43rossShardPhaseType\x12\x0b\n\x07PREPARE\x10\x00\x12\n\n\x06\x43OMMIT\x10\x01\x12\t\n\x05\x41\x42ORT\x10\x02\x62\x06proto3'
)

_CROSSSHARDPHASETYPE = _descriptor.EnumDescriptor(
  name='CrossShardPhaseType',
  full_name='CrossShardPhaseType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PREPARE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMIT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ABORT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=196,
  serialized_end=253,
)
_sym_db.RegisterEnumDescriptor(_CROSSSHARDPHASETYPE)

CrossShardPhaseType = enum_type_wrapper.EnumTypeWrapper(_CROSSSHARDPHASETYPE)
PREPARE = 0
COMMIT = 1
ABORT = 2



_CROSSSHARDREQ = _descriptor.Descriptor(
  name='CrossShardReq',
  full_name='CrossShardReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='phase', full_name='CrossShardReq.phase', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='senderClusterId', full_name='CrossShardReq.senderClusterId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receiverClusterId', full_name='CrossShardReq.receiverClusterId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='senderId', full_name='CrossShardReq.senderId', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receiverId', full_name='CrossShardReq.receiverId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='CrossShardReq.amount', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='CrossShardReq.id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=194,
)

_CROSSSHARDREQ.fields_by_name['phase'].enum_type = _CROSSSHARDPHASETYPE
DESCRIPTOR.message_types_by_name['CrossShardReq'] = _CROSSSHARDREQ
DESCRIPTOR.enum_types_by_name['CrossShardPhaseType'] = _CROSSSHARDPHASETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrossShardReq = _reflection.GeneratedProtocolMessageType('CrossShardReq', (_message.Message,), {
  'DESCRIPTOR' : _CROSSSHARDREQ,
  '__module__' : 'crossShardReq_pb2'
  # @@protoc_insertion_point(class_scope:CrossShardReq)
  })
_sym_db.RegisterMessage(CrossShardReq)


# @@protoc_insertion_point(module_scope)
