# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crossShardRsp.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crossShardRsp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63rossShardRsp.proto\"B\n\rCrossShardRsp\x12%\n\x06result\x18\x01 \x01(\x0e\x32\x15.CrossShardResultType\x12\n\n\x02id\x18\x02 \x01(\x05*0\n\x14\x43rossShardResultType\x12\x07\n\x03YES\x10\x00\x12\x06\n\x02NO\x10\x01\x12\x07\n\x03\x41\x43K\x10\x02\x62\x06proto3'
)

_CROSSSHARDRESULTTYPE = _descriptor.EnumDescriptor(
  name='CrossShardResultType',
  full_name='CrossShardResultType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='YES', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=91,
  serialized_end=139,
)
_sym_db.RegisterEnumDescriptor(_CROSSSHARDRESULTTYPE)

CrossShardResultType = enum_type_wrapper.EnumTypeWrapper(_CROSSSHARDRESULTTYPE)
YES = 0
NO = 1
ACK = 2



_CROSSSHARDRSP = _descriptor.Descriptor(
  name='CrossShardRsp',
  full_name='CrossShardRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CrossShardRsp.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='CrossShardRsp.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=89,
)

_CROSSSHARDRSP.fields_by_name['result'].enum_type = _CROSSSHARDRESULTTYPE
DESCRIPTOR.message_types_by_name['CrossShardRsp'] = _CROSSSHARDRSP
DESCRIPTOR.enum_types_by_name['CrossShardResultType'] = _CROSSSHARDRESULTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrossShardRsp = _reflection.GeneratedProtocolMessageType('CrossShardRsp', (_message.Message,), {
  'DESCRIPTOR' : _CROSSSHARDRSP,
  '__module__' : 'crossShardRsp_pb2'
  # @@protoc_insertion_point(class_scope:CrossShardRsp)
  })
_sym_db.RegisterMessage(CrossShardRsp)


# @@protoc_insertion_point(module_scope)
