# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intraShardRsp.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='intraShardRsp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13intraShardRsp.proto\"B\n\rIntraShardRsp\x12%\n\x06result\x18\x01 \x01(\x0e\x32\x15.IntraShardResultType\x12\n\n\x02id\x18\x02 \x01(\x05*-\n\x14IntraShardResultType\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x62\x06proto3'
)

_INTRASHARDRESULTTYPE = _descriptor.EnumDescriptor(
  name='IntraShardResultType',
  full_name='IntraShardResultType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=91,
  serialized_end=136,
)
_sym_db.RegisterEnumDescriptor(_INTRASHARDRESULTTYPE)

IntraShardResultType = enum_type_wrapper.EnumTypeWrapper(_INTRASHARDRESULTTYPE)
SUCCESS = 0
FAIL = 1



_INTRASHARDRSP = _descriptor.Descriptor(
  name='IntraShardRsp',
  full_name='IntraShardRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='IntraShardRsp.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='IntraShardRsp.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=89,
)

_INTRASHARDRSP.fields_by_name['result'].enum_type = _INTRASHARDRESULTTYPE
DESCRIPTOR.message_types_by_name['IntraShardRsp'] = _INTRASHARDRSP
DESCRIPTOR.enum_types_by_name['IntraShardResultType'] = _INTRASHARDRESULTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntraShardRsp = _reflection.GeneratedProtocolMessageType('IntraShardRsp', (_message.Message,), {
  'DESCRIPTOR' : _INTRASHARDRSP,
  '__module__' : 'intraShardRsp_pb2'
  # @@protoc_insertion_point(class_scope:IntraShardRsp)
  })
_sym_db.RegisterMessage(IntraShardRsp)


# @@protoc_insertion_point(module_scope)
