# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: printBalanceRsp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='printBalanceRsp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15printBalanceRsp.proto\"[\n\x0fPrintBalanceRsp\x12\x11\n\tclusterId\x18\x01 \x01(\x05\x12\x10\n\x08serverId\x18\x02 \x01(\x05\x12\x12\n\ndataItemID\x18\x03 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x04 \x01(\x05\x62\x06proto3'
)




_PRINTBALANCERSP = _descriptor.Descriptor(
  name='PrintBalanceRsp',
  full_name='PrintBalanceRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusterId', full_name='PrintBalanceRsp.clusterId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serverId', full_name='PrintBalanceRsp.serverId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataItemID', full_name='PrintBalanceRsp.dataItemID', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='balance', full_name='PrintBalanceRsp.balance', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['PrintBalanceRsp'] = _PRINTBALANCERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrintBalanceRsp = _reflection.GeneratedProtocolMessageType('PrintBalanceRsp', (_message.Message,), {
  'DESCRIPTOR' : _PRINTBALANCERSP,
  '__module__' : 'printBalanceRsp_pb2'
  # @@protoc_insertion_point(class_scope:PrintBalanceRsp)
  })
_sym_db.RegisterMessage(PrintBalanceRsp)


# @@protoc_insertion_point(module_scope)
