# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: printDatastoreRsp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import os, sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import proto.appendEntriesReq_pb2 as appendEntriesReq__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='printDatastoreRsp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17printDatastoreRsp.proto\x1a\x16\x61ppendEntriesReq.proto\"Q\n\x11PrintDatastoreRsp\x12\x11\n\tclusterId\x18\x01 \x01(\x05\x12\x10\n\x08serverId\x18\x02 \x01(\x05\x12\x17\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x06.Entryb\x06proto3'
  ,
  dependencies=[appendEntriesReq__pb2.DESCRIPTOR,])




_PRINTDATASTORERSP = _descriptor.Descriptor(
  name='PrintDatastoreRsp',
  full_name='PrintDatastoreRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusterId', full_name='PrintDatastoreRsp.clusterId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serverId', full_name='PrintDatastoreRsp.serverId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entries', full_name='PrintDatastoreRsp.entries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=132,
)

_PRINTDATASTORERSP.fields_by_name['entries'].message_type = appendEntriesReq__pb2._ENTRY
DESCRIPTOR.message_types_by_name['PrintDatastoreRsp'] = _PRINTDATASTORERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrintDatastoreRsp = _reflection.GeneratedProtocolMessageType('PrintDatastoreRsp', (_message.Message,), {
  'DESCRIPTOR' : _PRINTDATASTORERSP,
  '__module__' : 'printDatastoreRsp_pb2'
  # @@protoc_insertion_point(class_scope:PrintDatastoreRsp)
  })
_sym_db.RegisterMessage(PrintDatastoreRsp)


# @@protoc_insertion_point(module_scope)
