# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: printBalanceReq.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='printBalanceReq.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15printBalanceReq.proto\"J\n\x0fPrintBalanceReq\x12\x11\n\tclusterId\x18\x01 \x01(\x05\x12\x10\n\x08serverId\x18\x02 \x01(\x05\x12\x12\n\ndataItemID\x18\x03 \x01(\x05\x62\x06proto3'
)




_PRINTBALANCEREQ = _descriptor.Descriptor(
  name='PrintBalanceReq',
  full_name='PrintBalanceReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusterId', full_name='PrintBalanceReq.clusterId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serverId', full_name='PrintBalanceReq.serverId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataItemID', full_name='PrintBalanceReq.dataItemID', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['PrintBalanceReq'] = _PRINTBALANCEREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrintBalanceReq = _reflection.GeneratedProtocolMessageType('PrintBalanceReq', (_message.Message,), {
  'DESCRIPTOR' : _PRINTBALANCEREQ,
  '__module__' : 'printBalanceReq_pb2'
  # @@protoc_insertion_point(class_scope:PrintBalanceReq)
  })
_sym_db.RegisterMessage(PrintBalanceReq)


# @@protoc_insertion_point(module_scope)
