# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requestVoteRsp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='requestVoteRsp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14requestVoteRsp.proto\"3\n\x0eRequestVoteRsp\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\x62\x06proto3'
)




_REQUESTVOTERSP = _descriptor.Descriptor(
  name='RequestVoteRsp',
  full_name='RequestVoteRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='RequestVoteRsp.term', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voteGranted', full_name='RequestVoteRsp.voteGranted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['RequestVoteRsp'] = _REQUESTVOTERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestVoteRsp = _reflection.GeneratedProtocolMessageType('RequestVoteRsp', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTERSP,
  '__module__' : 'requestVoteRsp_pb2'
  # @@protoc_insertion_point(class_scope:RequestVoteRsp)
  })
_sym_db.RegisterMessage(RequestVoteRsp)


# @@protoc_insertion_point(module_scope)
