# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wrapperMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import os, sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import proto.stop_pb2 as stop__pb2
import proto.resume_pb2 as resume__pb2
import proto.intraShardReq_pb2 as intraShardReq__pb2
import proto.intraShardRsp_pb2 as intraShardRsp__pb2
import proto.crossShardReq_pb2 as crossShardReq__pb2
import proto.crossShardRsp_pb2 as crossShardRsp__pb2
import proto.appendEntriesReq_pb2 as appendEntriesReq__pb2
import proto.appendEntriesRsp_pb2 as appendEntriesRsp__pb2
import proto.requestVoteReq_pb2 as requestVoteReq__pb2
import proto.requestVoteRsp_pb2 as requestVoteRsp__pb2
import proto.printBalanceReq_pb2 as printBalanceReq__pb2
import proto.printBalanceRsp_pb2 as printBalanceRsp__pb2
import proto.printDatastoreReq_pb2 as printDatastoreReq__pb2
import proto.printDatastoreRsp_pb2 as printDatastoreRsp__pb2
import proto.exit_pb2 as exit__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wrapperMessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14wrapperMessage.proto\x1a\nstop.proto\x1a\x0cresume.proto\x1a\x13intraShardReq.proto\x1a\x13intraShardRsp.proto\x1a\x13\x63rossShardReq.proto\x1a\x13\x63rossShardRsp.proto\x1a\x16\x61ppendEntriesReq.proto\x1a\x16\x61ppendEntriesRsp.proto\x1a\x14requestVoteReq.proto\x1a\x14requestVoteRsp.proto\x1a\x15printBalanceReq.proto\x1a\x15printBalanceRsp.proto\x1a\x17printDatastoreReq.proto\x1a\x17printDatastoreRsp.proto\x1a\nexit.proto\"\xfd\x04\n\x0eWrapperMessage\x12\x15\n\x04stop\x18\x01 \x01(\x0b\x32\x05.StopH\x00\x12\x19\n\x06resume\x18\x02 \x01(\x0b\x32\x07.ResumeH\x00\x12\'\n\rintraShardReq\x18\x03 \x01(\x0b\x32\x0e.IntraShardReqH\x00\x12\'\n\rintraShardRsp\x18\x04 \x01(\x0b\x32\x0e.IntraShardRspH\x00\x12\'\n\rcrossShardReq\x18\x05 \x01(\x0b\x32\x0e.CrossShardReqH\x00\x12\'\n\rcrossShardRsp\x18\x06 \x01(\x0b\x32\x0e.CrossShardRspH\x00\x12-\n\x10\x61ppendEntriesReq\x18\x07 \x01(\x0b\x32\x11.AppendEntriesReqH\x00\x12-\n\x10\x61ppendEntriesRsp\x18\x08 \x01(\x0b\x32\x11.AppendEntriesRspH\x00\x12)\n\x0erequestVoteReq\x18\t \x01(\x0b\x32\x0f.RequestVoteReqH\x00\x12)\n\x0erequestVoteRsp\x18\n \x01(\x0b\x32\x0f.RequestVoteRspH\x00\x12+\n\x0fprintBalanceReq\x18\x0b \x01(\x0b\x32\x10.PrintBalanceReqH\x00\x12+\n\x0fprintBalanceRsp\x18\x0c \x01(\x0b\x32\x10.PrintBalanceRspH\x00\x12/\n\x11printDatastoreReq\x18\r \x01(\x0b\x32\x12.PrintDatastoreReqH\x00\x12/\n\x11printDatastoreRsp\x18\x0e \x01(\x0b\x32\x12.PrintDatastoreRspH\x00\x12\x15\n\x04\x65xit\x18\x0f \x01(\x0b\x32\x05.ExitH\x00\x42\x0e\n\x0cmessage_typeb\x06proto3'
  ,
  dependencies=[stop__pb2.DESCRIPTOR,resume__pb2.DESCRIPTOR,intraShardReq__pb2.DESCRIPTOR,intraShardRsp__pb2.DESCRIPTOR,crossShardReq__pb2.DESCRIPTOR,crossShardRsp__pb2.DESCRIPTOR,appendEntriesReq__pb2.DESCRIPTOR,appendEntriesRsp__pb2.DESCRIPTOR,requestVoteReq__pb2.DESCRIPTOR,requestVoteRsp__pb2.DESCRIPTOR,printBalanceReq__pb2.DESCRIPTOR,printBalanceRsp__pb2.DESCRIPTOR,printDatastoreReq__pb2.DESCRIPTOR,printDatastoreRsp__pb2.DESCRIPTOR,exit__pb2.DESCRIPTOR,])




_WRAPPERMESSAGE = _descriptor.Descriptor(
  name='WrapperMessage',
  full_name='WrapperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stop', full_name='WrapperMessage.stop', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resume', full_name='WrapperMessage.resume', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intraShardReq', full_name='WrapperMessage.intraShardReq', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intraShardRsp', full_name='WrapperMessage.intraShardRsp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crossShardReq', full_name='WrapperMessage.crossShardReq', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crossShardRsp', full_name='WrapperMessage.crossShardRsp', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appendEntriesReq', full_name='WrapperMessage.appendEntriesReq', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appendEntriesRsp', full_name='WrapperMessage.appendEntriesRsp', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestVoteReq', full_name='WrapperMessage.requestVoteReq', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestVoteRsp', full_name='WrapperMessage.requestVoteRsp', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='printBalanceReq', full_name='WrapperMessage.printBalanceReq', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='printBalanceRsp', full_name='WrapperMessage.printBalanceRsp', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='printDatastoreReq', full_name='WrapperMessage.printDatastoreReq', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='printDatastoreRsp', full_name='WrapperMessage.printDatastoreRsp', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exit', full_name='WrapperMessage.exit', index=14,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message_type', full_name='WrapperMessage.message_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=335,
  serialized_end=972,
)

_WRAPPERMESSAGE.fields_by_name['stop'].message_type = stop__pb2._STOP
_WRAPPERMESSAGE.fields_by_name['resume'].message_type = resume__pb2._RESUME
_WRAPPERMESSAGE.fields_by_name['intraShardReq'].message_type = intraShardReq__pb2._INTRASHARDREQ
_WRAPPERMESSAGE.fields_by_name['intraShardRsp'].message_type = intraShardRsp__pb2._INTRASHARDRSP
_WRAPPERMESSAGE.fields_by_name['crossShardReq'].message_type = crossShardReq__pb2._CROSSSHARDREQ
_WRAPPERMESSAGE.fields_by_name['crossShardRsp'].message_type = crossShardRsp__pb2._CROSSSHARDRSP
_WRAPPERMESSAGE.fields_by_name['appendEntriesReq'].message_type = appendEntriesReq__pb2._APPENDENTRIESREQ
_WRAPPERMESSAGE.fields_by_name['appendEntriesRsp'].message_type = appendEntriesRsp__pb2._APPENDENTRIESRSP
_WRAPPERMESSAGE.fields_by_name['requestVoteReq'].message_type = requestVoteReq__pb2._REQUESTVOTEREQ
_WRAPPERMESSAGE.fields_by_name['requestVoteRsp'].message_type = requestVoteRsp__pb2._REQUESTVOTERSP
_WRAPPERMESSAGE.fields_by_name['printBalanceReq'].message_type = printBalanceReq__pb2._PRINTBALANCEREQ
_WRAPPERMESSAGE.fields_by_name['printBalanceRsp'].message_type = printBalanceRsp__pb2._PRINTBALANCERSP
_WRAPPERMESSAGE.fields_by_name['printDatastoreReq'].message_type = printDatastoreReq__pb2._PRINTDATASTOREREQ
_WRAPPERMESSAGE.fields_by_name['printDatastoreRsp'].message_type = printDatastoreRsp__pb2._PRINTDATASTORERSP
_WRAPPERMESSAGE.fields_by_name['exit'].message_type = exit__pb2._EXIT
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['stop'])
_WRAPPERMESSAGE.fields_by_name['stop'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['resume'])
_WRAPPERMESSAGE.fields_by_name['resume'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['intraShardReq'])
_WRAPPERMESSAGE.fields_by_name['intraShardReq'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['intraShardRsp'])
_WRAPPERMESSAGE.fields_by_name['intraShardRsp'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['crossShardReq'])
_WRAPPERMESSAGE.fields_by_name['crossShardReq'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['crossShardRsp'])
_WRAPPERMESSAGE.fields_by_name['crossShardRsp'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['appendEntriesReq'])
_WRAPPERMESSAGE.fields_by_name['appendEntriesReq'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['appendEntriesRsp'])
_WRAPPERMESSAGE.fields_by_name['appendEntriesRsp'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['requestVoteReq'])
_WRAPPERMESSAGE.fields_by_name['requestVoteReq'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['requestVoteRsp'])
_WRAPPERMESSAGE.fields_by_name['requestVoteRsp'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['printBalanceReq'])
_WRAPPERMESSAGE.fields_by_name['printBalanceReq'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['printBalanceRsp'])
_WRAPPERMESSAGE.fields_by_name['printBalanceRsp'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['printDatastoreReq'])
_WRAPPERMESSAGE.fields_by_name['printDatastoreReq'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['printDatastoreRsp'])
_WRAPPERMESSAGE.fields_by_name['printDatastoreRsp'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
_WRAPPERMESSAGE.oneofs_by_name['message_type'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['exit'])
_WRAPPERMESSAGE.fields_by_name['exit'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['message_type']
DESCRIPTOR.message_types_by_name['WrapperMessage'] = _WRAPPERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WrapperMessage = _reflection.GeneratedProtocolMessageType('WrapperMessage', (_message.Message,), {
  'DESCRIPTOR' : _WRAPPERMESSAGE,
  '__module__' : 'wrapperMessage_pb2'
  # @@protoc_insertion_point(class_scope:WrapperMessage)
  })
_sym_db.RegisterMessage(WrapperMessage)


# @@protoc_insertion_point(module_scope)
